import os

from langchain.chat_models import init_chat_model
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()


# Structured Output
class ResponseGeneratorOutputFormat(BaseModel):
    ai_answer: str = Field(
        description="This value holds the answer generated by the AI assistant based on the user query and provided context."
    )


def create_response_generator_chain():

    # Prompt Template
    system_prompt = """
    You are a helpful AI assistant that is an expert in answering the user query based on the provided context.
    When you are answering a code snippet, please answer it in such a way that it can be rendered in markdown format as a code snippet.
    If the provided context is not relevant to the user query or is insufficient to answer the user query, please admit it honestly.
    Do not try to hallucinate and generate response that is not from the provided context. 
    If you receive a warning from the human stating that hallucination occurs before, please become more reserved in generating your answer by referring more to the provided context.
    Whenever you use any of the provided context, make sure you cite the source at the end of that sentence with numerical citations.
    The citation number that represents the citation should be based on the sequence of appearance in the answer instead of the sequence in the provided context.
    At the end of the response, please also have a reference section listing out the used citation ONLY, for example:

    The answer is abcd [1] and is proven by this source [2].
    
    References:
        [1] https://link.com
        [2] https://link2.com
    
    Do not skip the citation number sequencing when listing out the references or citations.
    """

    human_prompt = """
    {counter_hallucination_prompt}
    User Query: {user_query}
    Context: 
    {doc_content}
    """

    template = ChatPromptTemplate(
        [
            ("system", system_prompt),
            ("human", human_prompt),
        ],
    )

    # Initialize Model
    llm_model = init_chat_model(
        model=os.getenv("MODEL_NAME"),
        temperature=0,
    )
    llm_model_with_structured_output = llm_model.with_structured_output(
        ResponseGeneratorOutputFormat
    )

    # Initialize Chain
    return template | llm_model_with_structured_output
